name: Build Windows App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pip install flet
        timeout-minutes: 30
      - run: flet build windows --output dist
        timeout-minutes: 60
      - uses: actions/upload-artifact@v4
        with:
          name: env_manager-windows-x64
          path: dist/
          retention-days: 30
